# Generated by Django 5.2.10 on 2026-09-27 10:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCMachine',
            fields=[
                ('machine_code', models.CharField(help_text='Unique Machine Identifier (e.g. CNC-01)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Machine name (e.g. Fanuc Robodrill Alpha)', max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('controller_type', models.CharField(default='FANUC 0i-MF / 31i', max_length=50)),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.101')),
                ('port', models.PositiveIntegerField(default=8193)),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Timeout in seconds for FOCAS connection')),
                ('location', models.CharField(blank=True, default='Shop Floor Bay 1', max_length=100)),
                ('current_status', models.CharField(choices=[('RUNNING', 'Running'), ('IDLE', 'Idle'), ('ALARM', 'Alarm'), ('EMERGENCY_STOP', 'Emergency Stop'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=30)),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='machine_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CNC Machine',
                'verbose_name_plural': 'CNC Machines',
                'ordering': ['machine_code'],
            },
        ),
        migrations.CreateModel(
            name='FailureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MAN', 'Man (Personnel / Human Factor)'), ('MACHINE', 'Machine (Mechanical / Electrical Equipment)'), ('MATERIAL', 'Material (Raw Stock / Workpiece Defect)'), ('METHOD', 'Method (Program / Process / Feeds & Speeds)')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '4M Failure Category',
                'verbose_name_plural': '4M Failure Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('part_code', models.CharField(help_text='Unique Part / Tool Code (e.g. BRG-7014C)', max_length=50, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MECHANICAL', 'Mechanical (Bearings, Gears, Belts)'), ('ELECTRICAL', 'Electrical (Servos, Sensors, Contactors)'), ('PNEUMATIC', 'Pneumatic (Valves, Cylinders, Regulators)'), ('HYDRAULIC', 'Hydraulic (Seals, Pumps, Filters)'), ('TOOLING', 'Tooling / Inserts (Holders, Carbide Inserts)'), ('LUBRICANT', 'Lubricants & Oils (Spindle Oil, Waylube)'), ('CONSUMABLE', 'Consumables & Wipers')], default='MECHANICAL', max_length=50)),
                ('specification', models.CharField(blank=True, help_text='Technical dimensions or spec', max_length=200)),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces (pcs)'), ('SETS', 'Sets'), ('LTRS', 'Litres (L)'), ('METERS', 'Meters (m)'), ('PACKS', 'Packs')], default='PCS', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price', max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spare Part / Tool Catalog',
                'verbose_name_plural': 'Spare Parts & Tools Master',
                'ordering': ['part_code'],
            },
        ),
        migrations.CreateModel(
            name='FailureSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_code', models.CharField(help_text='e.g. MCH-SPN-01', max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. Spindle Bearing Overheat', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='maintenance.failurecategory')),
            ],
            options={
                'verbose_name': '4M Failure Sub-Category',
                'verbose_name_plural': '4M Failure Sub-Categories',
                'ordering': ['category', 'sub_category_code'],
            },
        ),
        migrations.CreateModel(
            name='BreakdownTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('trigger_source', models.CharField(choices=[('ALARM', 'CNC Alarm Triggered'), ('EMERGENCY', 'Emergency Stop Button Pressed'), ('IDLE_TIMEOUT', 'Prolonged Unproductive Idle'), ('MANUAL', 'Manual Technician / Operator Call')], default='ALARM', max_length=30)),
                ('status', models.CharField(choices=[('OPEN_ALARM', 'Open / Alarm Triggered'), ('ACKNOWLEDGED', 'Acknowledged / QR Scanned On-Site'), ('UNDER_REPAIR', 'Under Repair / Diagnosed'), ('RESOLVED', 'Resolved / Repair Complete'), ('CLOSED_RUNNING', 'Closed / Machine Resumed Production')], default='OPEN_ALARM', max_length=30)),
                ('shift', models.CharField(choices=[('Shift A', 'Shift A (06:00 - 14:00)'), ('Shift B', 'Shift B (14:00 - 22:00)'), ('Shift C', 'Shift C (22:00 - 06:00)')], default='Shift A', max_length=20)),
                ('focas_alarm_code', models.CharField(blank=True, max_length=50, null=True)),
                ('focas_alarm_msg', models.TextField(blank=True, null=True)),
                ('alarm_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of alarm / breakdown trigger (t_alarm)')),
                ('scan_time', models.DateTimeField(blank=True, help_text='Time technician scanned QR code at CNC (t_scan)', null=True)),
                ('diagnosed_time', models.DateTimeField(blank=True, help_text='Time 4M failure category was chosen', null=True)),
                ('resolve_time', models.DateTimeField(blank=True, help_text='Time repair & parts replacement completed (t_resolve)', null=True)),
                ('next_run_time', models.DateTimeField(blank=True, help_text='Time machine resumed cutting / running (t_run)', null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, help_text='t_scan - t_alarm (Mean Time to Acknowledge)', null=True)),
                ('repair_time_seconds', models.IntegerField(blank=True, help_text='t_resolve - t_scan (Active repair duration)', null=True)),
                ('total_downtime_seconds', models.IntegerField(blank=True, help_text='t_resolve - t_alarm (Total MTTR)', null=True)),
                ('ramp_up_delay_seconds', models.IntegerField(blank=True, help_text='t_run - t_resolve (Delay until production resume)', null=True)),
                ('symptom_notes', models.TextField(blank=True, help_text='Observed machine behavior or alarms')),
                ('resolution_notes', models.TextField(blank=True, help_text='Detailed actions taken to fix the issue')),
                ('total_spares_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='maintenance.cncmachine')),
                ('failure_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.failuresubcategory')),
            ],
            options={
                'verbose_name': 'Breakdown & Maintenance Ticket',
                'verbose_name_plural': 'Breakdown & Maintenance Tickets',
                'ordering': ['-alarm_time'],
            },
        ),
        migrations.CreateModel(
            name='MachineStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('IDLE', 'Idle'), ('ALARM', 'Alarm'), ('EMERGENCY_STOP', 'Emergency Stop'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('aut', models.IntegerField(blank=True, help_text='FANUC AUT mode', null=True)),
                ('run', models.IntegerField(blank=True, help_text='FANUC RUN status', null=True)),
                ('motion', models.IntegerField(blank=True, help_text='FANUC Motion status', null=True)),
                ('emergency', models.IntegerField(blank=True, help_text='FANUC Emergency flag', null=True)),
                ('alarm', models.IntegerField(blank=True, help_text='FANUC Alarm flag', null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='maintenance.cncmachine')),
            ],
            options={
                'verbose_name': 'Machine State Telemetry Log',
                'verbose_name_plural': 'Machine State Telemetry Logs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TicketSpareUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit_price_at_use', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='maintenance.sparepart')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares_used', to='maintenance.breakdownticket')),
            ],
            options={
                'verbose_name': 'Replaced Spare / Tool',
                'verbose_name_plural': 'Replaced Spares & Tools',
            },
        ),
    ]
