# Generated by Django 5.2.10 on 2026-10-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_cnc_machine_last_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(help_text='Unique Line Code (e.g. LINE-01)', max_length=50, unique=True, verbose_name='Line Code')),
                ('name', models.CharField(help_text='Descriptive Line Name (e.g. Crankshaft Machining Line)', max_length=100, verbose_name='Line Name')),
                ('location', models.CharField(blank=True, default='Shop Floor Bay 1', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['line_code'],
            },
        ),
        migrations.AddField(
            model_name='cncmachine',
            name='production_line',
            field=models.ForeignKey(blank=True, help_text='Select Production Line from Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='maintenance.productionline', verbose_name='Line'),
        ),
    ]
